apiVersion: v1
kind: Secret
metadata:
  name: {{ include "f5-securechat-enterprise.fullname" . }}-secret
  labels:
    {{- include "f5-securechat-enterprise.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ required "MANDATORY FIELD MISSING: env.apiKey must be provided! Pass --set env.apiKey=<your-f5-api-key>" .Values.env.apiKey | quote }}
  project-id: {{ required "MANDATORY FIELD MISSING: env.projectId must be provided! Pass --set env.projectId=<your-f5-project-id>" .Values.env.projectId | quote }}
  base-url: {{ required "MANDATORY FIELD MISSING: env.baseUrl must be provided! Pass --set env.baseUrl=https://<your-f5-portal-url>" .Values.env.baseUrl | quote }}
